#!/usr/bin/env python
import argparse
import os.path
from tcss455group7 import baseline

parser = argparse.ArgumentParser(description='455team7 project')
parser.add_argument('-i', help='input directory', type=str)
parser.add_argument('-o', help='output directory', type=str)
args = parser.parse_args()

if (args.i == None or
    args.o == None):
  parser.print_help()
  exit()
if (not os.path.exists(args.i) or
    not os.path.exists(args.o)):
  print 'Input or output directory does not exist.'
  exit()
if (os.path.isfile(args.i) or
    os.path.isfile(args.o)):
  print 'Input or output directory is not a directory.'
  exit()

print "Selected input directory: %s" % (args.i)
print "Selected output directory: %s" % (args.o)

processor = baseline.baseline()
processor.process(input_dir=args.i, output_dir=args.o)
